name: Pruebas Automatizadas (CI/CD)

on: ["push"]

jobs:
  qa_robot:
    runs-on: ubuntu-latest

    steps:
    - name: Descargando repositorio...
      uses: actions/checkout@v3

    - name: Instalando Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Corriendo Tests con Pytest
      run: |
        pytest -v