name: Pruebas Automatizadas (CI/CD)

on: ["push"]

jobs:
  qa_robot:
    runs-on: ubuntu-latest

    steps:
    - name: Descargando repositorio...
      uses: actions/checkout@v3

    - name: Instalando Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Corriendo Tests con Pytest
      run: |
        pytest -v --html=reportes/reporte.html --self-contained-html

    # Paso 5: Guardar el reporte en la nube (Artifact)
    - name: Subir Reporte HTML
      if: always()  # Â¡Importante! Se ejecuta aunque fallen los tests
      uses: actions/upload-artifact@v4
      with:
        name: reporte-de-pruebas
        path: reportes/reporte.html